### PR TITLE
Fix negative DelaySeconds being passed to parameter.

### LINKED ISSUE #106: Negative delay seconds are passed to the DelaySeconds parameter when setting a 0-second delay.
```
$ MyJob.set(wait: 0).perform_later
=> send_message(delay_seconds:-1,...)
::Failed to queue job #<GeneralJob:0x0000ffff94094040>. Reason: Value -1 for parameter DelaySeconds is invalid. DelaySeconds must be >= 0 and <= 900
```

I would submit PR later.

### PR DESCRIPTION
**Pull request by kyto64**
*Resolves #106*

*Description of changes:*

I fixed delay time to be 0 seconds when no delay or negative delay is set.

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by alextwoods — APPROVED** [review]
Thanks for the fix!

**Comment by mullermp** [comment]
Could we fix Rubocop please?

**Comment by kyto64** [comment]
Resolves #107

**Comment by kyto64** [comment]
> Could we fix Rubocop please?
fixed.

@mullermp @alextwoods 
Could you approve the PR again?

**Review by alextwoods — APPROVED** [review]
LGTM!

**Comment by kyto64** [comment]
Hi, how is your progress? 
We would appreciate it if you could release it as soon as possible.
Thanks.

**Comment by kyto64** [comment]
@mullermp 
Hi, how is your progress? 
We would appreciate it if you could release it as soon as possible.
Thanks.

**Comment by mullermp** [comment]
I'm sorry, I got caught up with other things. I will do this today.

**Comment by mullermp** [comment]
Released as 3.9.1

**Comment by kyto64** [comment]
Thanks.

**Pull request merged**
